### ISSUE TITLE
Seems to break my app, what am I doing wrong?

### ISSUE THREAD

**Issue by HemalR** [bitspook/react-medium-editor-es6#1]
Disclaimer - noobie trying to learn, be gentle! 

I'm running React & Meteor and experimenting around. Trying to create an editor that uses Medium-Editor (and love the idea of props vs state to control the content) hence giving this a shot.

main.js

``` javascript

import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, IndexRoute, browserHistory } from 'react-router';
import Body from './components/emailEditor/body'

import App from './components/app';


const routes = (
    <Router history={browserHistory}>
        <Route path="/" component={App}>
             <IndexRoute component={Body}/>
        </Route>
    </Router>
);

Meteor.startup(() => {
    ReactDOM.render(routes, document.querySelector('.app-mounter'));
});

```

./components/emailEditor/body.js

``` javascript
import React, { Component } from 'react';


class Body extends Component {
    render() {
        return (
            <div>body</div>
        );
    }
}

export default Body;
```

That works fine - Renders 'body' on the page as expected.

I have installed this with npm install react-medium-editor-es6 --save

Now, the moment I import this (even without actually making use of the imported component, the app breaks - console goes mental being unable to load any script).

``` javascript
import React, { Component } from 'react';
import MediumEditor from 'react-medium-editor-es6';


class Body extends Component {
    render() {
        return (
            <div>body</div>
        );
    }
}

export default Body;
```

<img width="538" alt="infobite" src="https://cloud.githubusercontent.com/assets/15634303/18501645/91c0e9a0-7a84-11e6-9e9b-463f7c8c31c4.png">

What am I missing? 

Thanks in advance to anyone who can help!

**Comment by bitspook** [comment]
Hey @HemalR,

I haven't worked with Meteor in a while. I am not sure how Meteor handles transpiling. Have you added a way to tell Meteor that this package is using es6 syntax and not es5 (as instructed in [readme](https://github.com/channikhabra/react-medium-editor-es6#installation) ? My guess is that meteor loads npm modules assuming they're using CommonJS modules, and fails when it find ES6 modules used in this package.

You can always verify this by copy-pasting `https://github.com/channikhabra/react-medium-editor-es6/blob/master/src/editor.js` file in your code, and importing that.

**Comment by HemalR** [comment]
Thanks for the help!

Apologies for the delayed gratitude - was offline for a few days.

Ended up getting a related meteor specific package working (mainly because I'm a noobie and wasn't able to figure this out :/ ). Will need to give it a whack just to understand how it works.

Thanks again!
