### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by didair** [bitspook/react-medium-editor-es6#2]
`SyntaxError: Unexpected keyword 'import'`

```
import Editor from './editor';

export default Editor;
```

I reckon its from the /src/index.js . Thats about it.

**Comment by bitspook** [comment]
Hello,

This component uses ES6 modules. So you'll have to put it somewhere in your project's transpilation step as mentioned in the [Installation step in readme](https://github.com/channikhabra/react-medium-editor-es6#installation)

Or, you can use the react-medium-editor component https://github.com/wangzuo/react-medium-editor

**Comment by bitspook** [comment]
I am closing this issue. As this package is explicitly built to be distributed as es6 module. You need to add it in your build process. You always have the option to use the original component: https://github.com/wangzuo/react-medium-editor
