### ISSUE TITLE
create-react-app: You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by wiradikusuma** [bitspook/react-medium-editor-es6#3]
I use https://github.com/facebook/create-react-app and it comes with ES6 and Babel, but I can't make this component to work:

	./node_modules/react-medium-editor-es6/src/editor.js
	Module parse failed: /Users/wiradikusuma/Documents/.../client/node_modules/react-medium-editor-es6/src/editor.js Unexpected token (14:21)
	You may need an appropriate loader to handle this file type.
	| 
	| export default class MediumEditor extends Component {
	|     static propTypes = {
	|         tag: PropTypes.string,
	|         text: PropTypes.string,

I'm missing something?

**Comment by bitspook** [comment]
Hello @wiradikusuma,

As mentioned in the [installation step](https://github.com/channikhabra/react-medium-editor-es6#installation), you need to include this module in babel-loader's configuration so it can get transpiled with rest of the ES6 code. Evidently, [create-react-app won't let you do that ](https://github.com/facebook/create-react-app/issues/3889).

Perhaps you should use the [original component](https://github.com/wangzuo/react-medium-editor) (the one this package is forked from).
